module.exports = [
  [ 1, {name: "Mobile" } ],
  [ 2, {name: "Android"} ],
  [ 3, {name: "PC (Microsoft Windows)" } ],
  [ 4, {name: "Xbox One"} ],
  [ 5, {name: "PlayStation 4" } ],
  [ 6, {name: "Nintendo Switch" } ],
  [ 7, {name: "PlayStation 3" } ],
  [ 8, {name: "PlayStation 2" } ],
  [ 9, {name: "PlayStation" } ],
  [ 10, {name: "PlayStation Vita" } ],
  [ 11, {name: "PlayStation Portable" } ],
  [ 12, {name: "Wii U" } ],
  [ 13, {name: "Wii"} ],
  [ 14, {name: "Nintendo GameCube"} ],
  [ 15, {name: "Nintendo 64" } ],
  [ 16, {name: "Super Nintendo Entertainment System (SNES)" } ],
  [ 17, {name: "Nintendo Entertainment System (NES)" } ],
  [ 18, {name: "New Nintendo 3DS" } ],
  [ 19, {name: "Nintendo 3DS" } ],
  [ 20, {name: "Nintendo DS" } ],
  [ 21, {name: "Xbox 360" } ],
  [ 22, {name: "Xbox" } ],
  [ 23, {name: "Mac" } ],
  [ 23, {name: "Linux" } ],
];
